### PR TITLE
Removing console.log

### PR DESCRIPTION
**Pull request by melanef**
Removing unconditional console.log

### CODE REVIEW

**Comment by melanef** [comment]
Hey @wuori 
Thanks for accepting the PR. After this, was the NPM package updated with a new version/tag? Or if I npm install it, will it still import the old version?

**Comment by wuori** [comment]
@melanef I'm sorry, this got lost in my inbox! I'll see if I can bump it tomorrow!

**Comment by wuori** [comment]
@melanef It's been bumped and published. Sorry about the long wait!

**Comment by melanef** [comment]
@wuori No worries, thanks a lot for this!

**Pull request merged**
